import React from 'react';
import ProductItem from './ProductItem';

const products = [
    { id: 1, name: 'LeapFrog Learning Friends 100 Words Book, Green', description: 'Join animal friends Turtle, Tiger and Monkey as they explore new vocabulary in the Learning Friends 100 Words Book. Explore the colorful pages and touch each picture to hear the animals say toddler-appropriate words along with exciting facts and sound effects. Immerse your child in bilingual play by sliding the language switch to hear the words, songs and instructions in Spanish. Touch the pictures to hear silly sound effects in Fun Sounds mode or press the light-up star button to hear two learning songs. Discover new vocabulary with cute learning friends! Intended for ages 18+ months. Requires 2 AA batteries. Batteries included for demo purposes only. New batteries recommended for regular use.', image: 'https://m.media-amazon.com/images/I/71wQb2LWUkL._AC_SL1500_.jpg', Rating: 4.8, link: 'https://www.amazon.com/LeapFrog-Learning-Friends-Words-Green/dp/B07B6ZN7P8/ref=sr_1_2?_encoding=UTF8&content-id=amzn1.sym.b378ed84-9ce7-4534-ab5a-a5a362ea6b4e&dib=eyJ2IjoiMSJ9.I7RuAdeRHNnoJg3tZQ2s5NtzvVhqgtOOO0tMjKVHyKIvSO61v0t4OY13edf7VpIOY_DA04t2Rl59y9d0sHdXdhGQcSc2QgltJU1qd3JuMS7zuTEgi3vnTTouYMMpF8z31K8dVZs23iGSOJj3UZNpFljr0CevoQz8YNlrNgmIV0xVRfQNn7HAghu5uDQrfiBg1UQVsKIsGGzucFdBHgCw5MM0AbXy7dV_QBCDEZ7m7iE0WmtGhHxhlr94X3vG4av0-2mDPDLe509jXlAJB36m9pN0SzqZm9st472A_X1xZwQ.8AeLOqofC4eUSwpujJMnyhPXl_aF8s52eqr5clekWM4&dib_tag=se&keywords=learning%2Btoys&pd_rd_r=0844d95d-f3bc-469c-8068-d1f458d48691&pd_rd_w=bQ8b7&pd_rd_wg=GUrDz&pf_rd_p=b378ed84-9ce7-4534-ab5a-a5a362ea6b4e&pf_rd_r=MBRAKBSP9Q5A2D5CJ33B&qid=1718612263&sr=8-2&th=1' },
    { id: 2, name: 'VTech Touch and Learn Activity Desk Deluxe (Frustration Free Packaging)', description: 'The Touch and Learn Activity Desk Deluxe by VTech is a 3-in-1 toddler activity center with 5 separate activity pages packed full of fun ways to learn! The desk itself features an interactive desktop and pages of activities to explore educational subjects like letters, numbers, music, colors and more. Choose from 8 expansion packs (each sold separately) to focus on a specific curriculum like nursery rhymes, reading skills, animals, and numbers. The toddler play table features 100+ vocabulary words, 20+ activities and 20+ songs. It also transforms from a toy desk and chair into an easel and a chalkboard with plenty of storage space for art supplies to encourage play and discovery. The LED display illustrates letter and number stroke order and how to draw basic shapes. ', image: 'https://m.media-amazon.com/images/I/612vMyfT8zL._AC_SL1001_.jpg', rating: 4.7, link: 'https://www.amazon.com/VTech-Activity-Deluxe-Frustration-Packaging/dp/B01FVS6V9Y/ref=sr_1_7?_encoding=UTF8&content-id=amzn1.sym.b378ed84-9ce7-4534-ab5a-a5a362ea6b4e&dib=eyJ2IjoiMSJ9.I7RuAdeRHNnoJg3tZQ2s5NtzvVhqgtOOO0tMjKVHyKIvSO61v0t4OY13edf7VpIOY_DA04t2Rl59y9d0sHdXdhGQcSc2QgltJU1qd3JuMS7zuTEgi3vnTTouYMMpF8z31K8dVZs23iGSOJj3UZNpFljr0CevoQz8YNlrNgmIV0xVRfQNn7HAghu5uDQrfiBg1UQVsKIsGGzucFdBHgCw5MM0AbXy7dV_QBCDEZ7m7iE0WmtGhHxhlr94X3vG4av0-2mDPDLe509jXlAJB36m9pN0SzqZm9st472A_X1xZwQ.8AeLOqofC4eUSwpujJMnyhPXl_aF8s52eqr5clekWM4&dib_tag=se&keywords=learning%2Btoys&pd_rd_r=0844d95d-f3bc-469c-8068-d1f458d48691&pd_rd_w=bQ8b7&pd_rd_wg=GUrDz&pf_rd_p=b378ed84-9ce7-4534-ab5a-a5a362ea6b4e&pf_rd_r=MBRAKBSP9Q5A2D5CJ33B&qid=1718612263&sr=8-7&th=1' },
    { id: 3, name: 'LeapFrog My Own Leaptop, 2 - 4 years, Green', description: 'Leap into letters and animals with this perfectly sized laptop toy. Lift the lid to reveal 26 letter buttons to push and explore, each introducing its name and sound. Pressing the buttons also displays an animation of an animal that begins with that letter. Encourage kids to practice spelling their names by personalizing the little laptop. Get to work playing pretend and exchange emails with puppy pal Scout. Writing emails to you makes him happy! Play animal trivia and letter games that introduce animal facts and ask kids to choose the correct answer by pressing a letter button.', image: 'https://m.media-amazon.com/images/I/61quHjcEqIL._AC_SL1000_.jpg', rating: 4.7, link: 'https://www.amazon.com/LeapFrog-My-Own-Leaptop-Green/dp/B0038AJYSS/ref=sr_1_18?_encoding=UTF8&content-id=amzn1.sym.b378ed84-9ce7-4534-ab5a-a5a362ea6b4e&dib=eyJ2IjoiMSJ9.I7RuAdeRHNnoJg3tZQ2s5NtzvVhqgtOOO0tMjKVHyKIvSO61v0t4OY13edf7VpIOY_DA04t2Rl59y9d0sHdXdhGQcSc2QgltJU1qd3JuMS7zuTEgi3vnTTouYMMpF8z31K8dVZs23iGSOJj3UZNpFljr0CevoQz8YNlrNgmIV0xVRfQNn7HAghu5uDQrfiBg1UQVsKIsGGzucFdBHgCw5MM0AbXy7dV_QBCDEZ7m7iE0WmtGhHxhlr94X3vG4av0-2mDPDLe509jXlAJB36m9pN0SzqZm9st472A_X1xZwQ.8AeLOqofC4eUSwpujJMnyhPXl_aF8s52eqr5clekWM4&dib_tag=se&keywords=learning%2Btoys&pd_rd_r=0844d95d-f3bc-469c-8068-d1f458d48691&pd_rd_w=bQ8b7&pd_rd_wg=GUrDz&pf_rd_p=b378ed84-9ce7-4534-ab5a-a5a362ea6b4e&pf_rd_r=MBRAKBSP9Q5A2D5CJ33B&qid=1718612263&sr=8-18&th=1' },
    { id: 4, name: 'Fisher-Price Laugh & Learn Smart Stages Puppy', description: 'Fisher-Price Laugh & Learn Smart Stages Puppy is soft, cuddly, and he\'s ready to make sure learning fun never ends. This plush puppy responds to your baby\'s touch with exciting sing-along songs and phrases that introduce more than 100 first words, parts of the body, colors, shapes, and more! And because every baby develops at their own pace, Smart Stages technology lets you select the level that\'s best for your child. There are a variety of songs, sounds and phrases within each of the three levels of play. And Puppy\'s light-up, multicolor heart even twinkles along to the music!', image: 'https://m.media-amazon.com/images/I/71M9jsP2KTL._AC_UL640_QL65_.jpg', rating: 4.8, link: 'https://shorturl.at/W3obi' },
    { id: 5, name: 'Melissa & Doug Shape Sorting Cube Classic Wooden Toy', description: 'This classic wooden shape sorting toy from Melissa & Doug is fun and educational! The shape sorting cube includes 12 easy-to-grip, vibrant shapes that fit into the matching holes in the wooden cube. The cube features durable construction and helps to promote hand-eye coordination, fine motor skills, and problem-solving skills.', image: 'https://m.media-amazon.com/images/I/71W0K0nMd5L._AC_UL640_QL65_.jpg', rating: 4.9, link: '' },
    { id: 6, name: 'LeapFrog 2-in-1 LeapTop Touch', description: 'The LeapFrog 2-in-1 LeapTop Touch is a laptop designed for kids that transforms into a touch screen tablet. It features a keyboard with letters and numbers, and a touch screen for interactive play. Kids can pretend to send emails, play alphabet games, and learn about animals and their sounds. The LeapTop Touch is ideal for ages 2-4 and helps develop language and communication skills.', image: 'https://m.media-amazon.com/images/I/61fvlT1I-EL._AC_SL1000_.jpg', rating: 4.5, link: 'https://www.amazon.com/LeapFrog-2-1-LeapTop-Touch/dp/B01MR5EF5D/ref=sr_1_12?_encoding=UTF8&content-id=amzn1.sym.b378ed84-9ce7-4534-ab5a-a5a362ea6b4e&keywords=learning%2Btoys&qid=1718612263&sr=8-12' },
    { id: 7, name: 'VTech KidiBeats Drum Set', description: 'The VTech KidiBeats Drum Set is a fun and educational toy for young children. It features three drum pads and a cymbal, each with its own unique sound for sensory development. Kids can play along to nine melodies in various styles, including rock, dance, and pop. Learning modes teach letters, numbers, and music with fun and interactive games. The drum set is great for developing fine motor skills and encouraging a love of music.', image: 'https://m.media-amazon.com/images/I/81CTi+EyOKL._AC_SL1500_.jpg', rating: 4.6, link: 'https://www.amazon.com/VTech-KidiBeats-Drum-Set-Frustration/dp/B00DW1JT5G/ref=sr_1_20?_encoding=UTF8&content-id=amzn1.sym.b378ed84-9ce7-4534-ab5a-a5a362ea6b4e&keywords=learning%2Btoys&qid=1718612263&sr=8-20' },
    { id: 8, name: 'Fisher-Price Think & Learn Code-a-pillar', description: 'The Fisher-Price Think & Learn Code-a-pillar is an interactive learning toy that encourages children to experiment as they play, helping them develop important skills like problem-solving, planning, and sequencing. The Code-a-pillar is made up of 8 segments that preschoolers can arrange and rearrange to "program" different paths for the Code-a-pillar to follow. It is an innovative way to introduce young learners to the concepts of coding and technology.', image: 'https://m.media-amazon.com/images/I/81MZQDY8CkL._AC_SL1500_.jpg', rating: 4.2, link: 'https://shorturl.at/V2sAT' },
    { id: 9, name: 'Playskool Sit n Spin Classic Spinning Activity Toy for Toddlers', description: 'The Playskool Sit n Spin toy has been a classic for generations! This version of the classic spinning toy helps toddlers practice balance, coordination, and motor skills as they spin the wheel to make the base move. It is a great way for kids to burn off energy and have fun indoors. The Sit n Spin is designed for children ages 18 months and up and is perfect for solo play or playdates.', image: 'https://m.media-amazon.com/images/I/71ZhBXgcTTL._AC_UL640_QL65_.jpg',rating: 4.7, link: 'https://www.amazon.com/Playskool-Classic-Spinning-Activity-Toddlers/dp/B00YTWEMUO/ref=sr_1_2?crid=RR5N1J40VA8N&dib=eyJ2IjoiMSJ9.KHFs3Rnse_HmU10gLy27xu7mxKw0IeUQ3Z7m0C8k8y_USI6BnhQdTgWg6h18jKv_TCS3WyzE_I17tT23iuRa_2N5kVoK6yFXwDlFnT3XAyPTcHEswzSmKiIZrlRE5o_XBGpHMIzidNRFiYHZrMZ1WqUzV2YPK2rBVv1k-ZJAtMSYTembHskwqBKndl2NA3bPfzRFFNA-0cScCcMJW0le843hgV6cuZrM0N6cfplZDbNjae8x7jEcRVNDwnBCdxEX7SqNKp3D0w-oGytAhUq1gfFF2HCMsedNFRwIqD5x-tw.o_Wp1uvQc0yx2FPVYoU0M-fd8ZAY3DDjk_pR_tG7Iys&dib_tag=se&keywords=playskool+sit+and+spin&qid=1718613590&sprefix=playskool%2Caps%2C388&sr=8-2' },
    { id: 10, name: 'Fat Brain Toys Dimpl Baby Toy', description: 'Fat Brain Toys Dimpl is a simple yet innovative toy that will keep babies entertained for hours. It features five vibrant silicone bubbles built into a plastic frame. Push them in and out, poke them, prod them, and listen to them pop! Dimpl is perfect for sensory exploration and fine motor skills development. It\'s also great for on-the-go fun and is designed for babies and toddlers.', image: 'https://m.media-amazon.com/images/I/61ig9IQaxlL._AC_UL640_QL65_.jpg', rating: 4.8, link: 'https://www.amazon.com/Fat-Brain-Toys-FA192-1-Dimpl/dp/B079CH7PLF/ref=sr_1_1?crid=1PO4U2NUGHD58&dib=eyJ2IjoiMSJ9.kW6slHA5G3TLvrMCTCMzEzE9R7l0h_Rew3_lOeu02O3JaUCsXtjoPfsTQjxeA0n6PLX6fyW7MX10O_ZOPasqqL10x0SBCicvmBxoCl7A3vmSe8z1YiiXEL7O0Ukob-iUhqRA7aQ3uY9PSupc5FBzn_Db2kNpDNyd4czcnk3CCewMUqmj696OAuW_q_UpazERJ2asorHCcF5VTI6d2N-P8mRWRU58vStkU51WAxA5aw4M0W7-NidcnoebzTLbyzvGIKUbHiQ9Vz6IuU_NCCRspFLL2cTOe1vRAzBUXFiFFZ4.8vHtCm-Ca8W0oA8AakClSaopF7krqUrL0NL1osRFHpo&dib_tag=se&keywords=Fat+Brain+Toys+Dimpl+Baby+Toy&qid=1718613414&sprefix=fat+brain+toys+dimpl+baby+toy%2Caps%2C549&sr=8-1'},
  ];
  

const ProductList = () => (
  <div>
    <h2>Products</h2>
    {products.map(product => (
      <ProductItem key={product.id} product={product} />
    ))}
  </div>
);

export default ProductList;
